### ISSUE TITLE
Cape Bug Report

### ISSUE THREAD

**Issue by WeebleRabbit** [5zig-reborn/The-5zig-Mod#53] opened 2020-05-03 22:24 UTC
Capes seem to corrupt sometimes.

**To Reproduce**
1. Launch Minecraft
2. Login to a server
3. Sometimes it will be corrupted

**Expected behavior**
I expected it to not be corrupted?

**Screenshots**
https://cdn.discordapp.com/attachments/586624585311584266/706497426550423582/unknown.png

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I have:
Perspective Mod 3.0
CheatbreakerHUD 5.0
PotionEffectHUD 1.0
Powns ToggleSneak 3.0
Sidebar Mod Revamp
5zig Reborn
AutoGG
AutoTip
BetterChat
Frames+
Levelhead
Oof Mod
Optifine
Patcher
Quickplay, Quickplay Premium
Scrollable Tooltips
Sk1er's OldAnimations Mod
ToggleChat

**Comment by RoccoDev** [comment] 2020-05-05 13:52
I can't seem to reproduce the issue.  
However, I believe it is caused by the Frames+ mod, which I can't install on my system.

Could you try removing it temporarily and checking if the issue persists?

**Comment by RoccoDev** [comment] 2020-08-12 20:38
Closing in favor of #90

**Closed by RoccoDev** 2020-08-12 20:38 UTC
Labels: Bug
